import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children : React.ReactNode,
  modal : React.ReactNode
}

export default function RootLayout({
  children, modal
} : Props) {
  return (
    <html lang="ko">
      <body className={`bg-black`}>
        {children}
        {modal}
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
